version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Excute Create/Update Stack
          command: |
            aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE | grep sample-stack
            if [ $? -ne 0 ]; then
              aws cloudformation create-stack --stack-name sample-stack --template-body file://service/infrastructure.yml
              aws cloudformation wait stack-create-complete --stack-name sample-stack
            else
              aws cloudformation update-stack --stack-name sample-stack --template-body file://service/infrastructure.yml
              if [ $? -eq 255 ]; then
                exit 0
              elif [ $? -eq 0 ]; then
                aws cloudformation wait stack-update-complete --stack-name sample-stack
              fi
            fi

workflows:
  sample-workflow:
    jobs:
      - aws-cli
