version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Excute Create/Update Stack
          command: |
            aws cloudformation create-stack --stack-name sample-stack --template-body file://service/infrastructure.yml
            aws cloudformation wait stack-create-complete --stack-name sample-stack

workflows:
  sample-workflow:
    jobs:
      - aws-cli
